### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by garyrvaz** [ruucm/react-google-sheets#1]
Hey,
I am getting this error when importing the component.

ReferenceError: window is not defined
    at Object.<anonymous> (/home/yuuwaku/PaySense/web/node_modules/react-google-sheets/google-sheet-connector/gapi.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/yuuwaku/PaySense/web/node_modules/react-google-sheets/google-sheet-connector/index.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by Salamit** [comment]
Hi! I'm getting this issue as well

ReferenceError: window is not defined
W20190218-23:19:07.172(9)? (STDERR)     at Object.<anonymous> (/Users/user/Library/Mobile Documents/coding/Courses/meteor-projects/app/node_modules/react-google-sheets/google-sheet-connector/gapi.js:5:12)
W20190218-23:19:07.173(9)? (STDERR)     at Module._compile (module.js:652:30)
W20190218-23:19:07.173(9)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20190218-23:19:07.173(9)? (STDERR)     at Module.load (module.js:565:32)
W20190218-23:19:07.173(9)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20190218-23:19:07.174(9)? (STDERR)     at Function.Module._load (module.js:497:3)
W20190218-23:19:07.174(9)? (STDERR)     at Module.require (module.js:596:17)
W20190218-23:19:07.174(9)? (STDERR)     at require (internal/module.js:11:18)
W20190218-23:19:07.174(9)? (STDERR)     at Object.<anonymous> (/Users/user/Library/Mobile Documents/coding/Courses/meteor-projects/app/node_modules/react-google-sheets/google-sheet-connector/index.js:8:12)
W20190218-23:19:07.174(9)? (STDERR)     at Module._compile (module.js:652:30)
W20190218-23:19:07.175(9)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20190218-23:19:07.175(9)? (STDERR)     at Module.load (module.js:565:32)
W20190218-23:19:07.175(9)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20190218-23:19:07.175(9)? (STDERR)     at Function.Module._load (module.js:497:3)
W20190218-23:19:07.175(9)? (STDERR)     at Module.require (module.js:596:17)
W20190218-23:19:07.176(9)? (STDERR)     at require (internal/module.js:11:18)
W20190218-23:19:07.176(9)? (STDERR)     at Object.<anonymous> (/Users/user/Library/Mobile Documents/coding/Courses/meteor-projects/app/node_modules/react-google-sheets/ReactGoogleSheets.js:14:29)
W20190218-23:19:07.176(9)? (STDERR)     at Module._compile (module.js:652:30)
W20190218-23:19:07.176(9)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20190218-23:19:07.176(9)? (STDERR)     at Module.load (module.js:565:32)
W20190218-23:19:07.177(9)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20190218-23:19:07.177(9)? (STDERR)     at Function.Module._load (module.js:497:3)
=> Exited with code: 1
